### ISSUE TITLE
dial tcp6: no suitable address found

### ISSUE THREAD

**Issue by kaihendry** [prometheus/blackbox_exporter#74] opened 2016-11-05 07:30 UTC
I'm using:

```
Digest: sha256:0eaf1811c018de2d87d6d14ad848cd5fb2333b7d17eeb9da19a3101796e8f865
Status: Image is up to date for prom/blackbox-exporter:master
```

http://s.natalian.org/2016-11-05/blackboxexporter.txt

I guess I need to force tcp4 somehow, somewhere?

**Comment by brian-brazil** [comment] 2016-11-05 07:38
Dupe of #69

**Closed by brian-brazil** 2016-11-05 07:38 UTC

**Comment by kaihendry** [comment] 2016-11-05 07:48
Can I assume a new release will fix this? Or is some configuration change required?
