### ISSUE TITLE
http probe fails with 302 responses

### ISSUE THREAD

**Issue by prologic** [prometheus/blackbox_exporter#246] opened 2017-10-17 23:56 UTC
I have tried to setup blackbox_exporter to monitor some sites that by default return a 302 response. Neither `no_follow_redirect` (*which defaults to `false`*) works nor does setting a custom `valid_status_codes: [200, 302]` the probe still fails.

My only work around has been to reconfigure the targets to the location that the 302 response indicates.

Bug?

**Comment by prologic** [comment] 2017-10-17 23:57
Or maybe my expectation is wrong. I expect the probe to be able to follow redirects successfully and report success on the redirected response.

**Comment by brian-brazil** [comment] 2017-10-18 07:48
In what exact way is it failing? Can you share the debug output?

**Comment by sysadmind** [comment] 2017-10-20 17:03
I started having this issue as well. Maybe I can shed some light on this. 
Version:
```
blackbox_exporter_build_info{branch="HEAD",goversion="go1.9.1",revision="75681e3c4f051e24269a132e8ec19517118e1586",version="0.10.0"} 
```

Debug log (sanitized) 
```
Logs for the probe:
ts=2017-10-20T17:00:46.449250675Z caller=main.go:116 module=http_check_200 target=https://mysite.com/index.html level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2017-10-20T17:00:46.449369876Z caller=utils.go:43 module=http_check_200 target=https://mysite.com/index.html level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2017-10-20T17:00:46.45020119Z caller=utils.go:63 module=http_check_200 target=https://mysite.com/index.html level=info msg="Resolved target address" ip=1.2.3.4
ts=2017-10-20T17:00:46.450250232Z caller=http.go:190 module=http_check_200 target=https://mysite.com/index.html level=info msg="Making HTTP request" url=https://[1.2.3.4]/index.html host=mysite.com
ts=2017-10-20T17:00:46.605950399Z caller=http.go:150 module=http_check_200 target=https://mysite.com/index.html level=info msg="Received redirect" url="https://[1.2.3.4]/index.html?method=mymethod"
ts=2017-10-20T17:00:46.711399818Z caller=http.go:197 module=http_check_200 target=https://mysite.com/index.html level=info msg="Received HTTP response" status_code=400
ts=2017-10-20T17:00:46.71147354Z caller=http.go:206 module=http_check_200 target=https://mysite.com/index.html level=info msg="Invalid HTTP response status code" status_code=400 valid_status_codes=[200]
ts=2017-10-20T17:00:46.711523025Z caller=main.go:129 module=http_check_200 target=https://mysite.com/index.html level=error msg="Probe failed" duration_seconds=0.262219565
```

My understanding of the problem: The 302 redirect is to a relative path. blackbox_exporter does not keep the `Host` header on the redirect if it's a relative path without a new host.

**Comment by prologic** [comment] 2017-10-20 17:23
Oh thanks for debugging this! I hadn't gotten around to it myself! That's
very interesting and looks like a bug?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by brian-brazil** [comment] 2017-10-20 17:59
Dupe of #245

**Closed by brian-brazil** 2017-10-20 17:59 UTC

**Comment by 4volodin** [comment] 2023-04-24 07:33
I'm also having the same issue

**Comment by skundu1234** [comment] 2025-03-07 09:40
Team is there any update or anyone resolve this issue
