### ISSUE TITLE
Broken HTTPS redirects

### ISSUE THREAD

**Issue by sc0rp10** [prometheus/blackbox_exporter#511] opened 2019-08-16 15:36 UTC
It seems that blackbox_exporter does not handle https redirect properly.

For instance, I have a URL `https://foo.bar/baz` that redirects to `google.com`:
```
$ curl -I https://foo.bar/baz
HTTP/1.1 301 Moved Permanently
Location: https://google.com
```

I expect that this target will not fail in the case when the redirected locations works. However, this is not the case with blackbox_exporter. If I change the redirect location to a HTTP url, everything works fine.

### Host operating system: output of `uname -a`
`Linux bb 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`
### blackbox_exporter version: output of `blackbox_exporter -version`
```
# blackbox_exporter --version
blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:32:31
  go version:       go1.11.5
```

### What is the blackbox.yml module config.
```
---
modules:
  http_2xx:
    prober: http
    timeout: 3s
    http:
      method: HEAD
      preferred_ip_protocol: ip4
```
### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2019-08-16T15:08:21.866181972Z caller=main.go:118 module=http_2xx target=https://foo.bar/baz level=info msg="Beginning probe" probe=http timeout_seconds=2.5
ts=2019-08-16T15:08:21.866353269Z caller=utils.go:42 module=http_2xx target=https://foo.bar/baz level=info msg="Resolving target address" ip_protocol=ip4
ts=2019-08-16T15:08:21.867170371Z caller=utils.go:75 module=http_2xx target=https://foo.bar/baz level=info msg="Resolved target address" ip=104.27.190.48
ts=2019-08-16T15:08:21.867222715Z caller=http.go:349 module=http_2xx target=https://foo.bar/baz level=info msg="Making HTTP request" url=http://[104.27.190.48]/baz host=foo.bar
ts=2019-08-16T15:08:21.883849497Z caller=http.go:305 module=http_2xx target=https://foo.bar/baz level=info msg="Received redirect" url=https://google.com
ts=2019-08-16T15:08:21.958228803Z caller=http.go:364 module=http_2xx target=https://foo.bar/baz level=error msg="Error for HTTP request" err="Head https://google.com: x509: certificate is valid for *.google.com, *.android.com, *.appengine.google.com, *.cloud.google.com, *.crowdsource.google.com, *.g.co, *.gcp.gvt2.com, *.gcpcdn.gvt1.com, *.ggpht.cn, *.google-analytics.com, *.google.ca, *.google.cl, *.google.co.in, *.google.co.jp, *.google.co.uk, *.google.com.ar, *.google.com.au, *.google.com.br, *.google.com.co, *.google.com.mx, *.google.com.tr, *.google.com.vn, *.google.de, *.google.es, *.google.fr, *.google.hu, *.google.it, *.google.nl, *.google.pl, *.google.pt, *.googleadapis.com, *.googleapis.cn, *.googlecnapps.cn, *.googlecommerce.com, *.googlevideo.com, *.gstatic.cn, *.gstatic.com, *.gstaticcnapps.cn, *.gvt1.com, *.gvt2.com, *.metric.gstatic.com, *.urchin.com, *.url.google.com, *.youtube-nocookie.com, *.youtube.com, *.youtubeeducation.com, *.youtubekids.com, *.yt.be, *.ytimg.com, android.clients.google.com, android.com, developer.android.google.cn, developers.android.google.cn, g.co, ggpht.cn, goo.gl, google-analytics.com, google.com, googlecnapps.cn, googlecommerce.com, source.android.google.cn, urchin.com, www.goo.gl, youtu.be, youtube.com, youtubeeducation.com, youtubekids.com, yt.be, not foo.bar"
ts=2019-08-16T15:08:21.958301947Z caller=http.go:450 module=http_2xx target=https://foo.bar/baz level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-08-16T18:08:21.867309657+03:00 dnsDone=2019-08-16T18:08:21.867309657+03:00 connectDone=2019-08-16T18:08:21.868623966+03:00 gotConn=2019-08-16T18:08:21.86864028+03:00 responseStart=2019-08-16T18:08:21.883755849+03:00 end=0001-01-01T00:00:00Z
ts=2019-08-16T15:08:21.958335369Z caller=http.go:450 module=http_2xx target=https://foo.bar/baz level=info msg="Response timings for roundtrip" roundtrip=1 start=2019-08-16T18:08:21.883915096+03:00 dnsDone=2019-08-16T18:08:21.884326768+03:00 connectDone=2019-08-16T18:08:21.920375708+03:00 gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2019-08-16T15:08:21.958356773Z caller=main.go:131 module=http_2xx target=https://foo.bar/baz level=error msg="Probe failed" duration_seconds=0.092107658
```
### What did you expect to see?
Successful http check
### What did you see instead?
Failed http check

**Comment by brian-brazil** [comment] 2019-08-16 15:38
Dupe of #237

**Closed by brian-brazil** 2019-08-16 15:38 UTC
