### ISSUE TITLE
module HTTP: hostname resolved locally even when using a proxy

### ISSUE THREAD

**Issue by Scapal** [prometheus/blackbox_exporter#553] opened 2019-11-21 17:16 UTC
When using a proxy in a http probe, the http target address is resolved locally instead of letting the proxy server resolve it. 

Would it be possible to add an option that doesn't replace the targetURL with the IP address ?

https://github.com/prometheus/blackbox_exporter/blob/3a08e67780bcb728a42cbf00ba03e0bd363a8e8e/prober/http.go#L370

**Comment by brian-brazil** [comment] 2019-11-21 17:18
Dupe of #553.

**Closed by brian-brazil** 2019-11-21 17:18 UTC

**Comment by Scapal** [comment] 2019-11-21 17:21
@brian-brazil, it has nothing to do with forcing https described in #503 even if I first thought it was related.

**Comment by brian-brazil** [comment] 2019-11-21 17:34
So it is, #264 is probably closest then.
