### ISSUE TITLE
accept4: too many open files

### ISSUE THREAD

**Issue by pj42** [prometheus/blackbox_exporter#96] opened 2017-01-09 10:42 UTC
Hey,

Implemented blackbox exporter monitoring before the weekend and then came back into work today and checked my email and it had sent out many email alerts that all servers had failed which were actually responding fine. When I checked it had logged this error 121827 times:

    2017/01/07 00:09:37 http: Accept error: accept tcp 0.0.0.0:9115: accept4: too many open files; retrying in 10ms

And using lsof I could see that blackbox_exporter had 1015 connections open to two different services on the same machine. (Replaced some items with ********)

    blackbox_ 17824    ********  976u     IPv4           95427223        0t0       TCP ********:38874->********:cslistener (ESTABLISHED)
    blackbox_ 17824    ********  977u     IPv4           95442547        0t0       TCP ********:39260->********:cslistener (ESTABLISHED)
    blackbox_ 17824    ********  978u     IPv4           95435025        0t0       TCP ********:39104->********:cslistener (ESTABLISHED)
    blackbox_ 17824    ********  979u     IPv4           95450512        0t0       TCP ********:39491->********:cslistener (ESTABLISHED)
    blackbox_ 17824    ********  980u     IPv4           96097668        0t0       TCP ********:60702->********:personal-agent (ESTABLISHED)
    blackbox_ 17824    ********  981u     IPv4           95914370        0t0       TCP ********:56885->********:personal-agent (ESTABLISHED)
    blackbox_ 17824    ********  982u     IPv4           95464734        0t0       TCP ********:39803->********:cslistener (ESTABLISHED)

**Comment by brian-brazil** [comment] 2017-01-09 10:52
Sounds like a dupe of #84

**Closed by brian-brazil** 2017-01-09 10:52 UTC
