### ISSUE TITLE
Certificates are not correctly checked on redirections

### ISSUE THREAD

**Issue by guilro** [prometheus/blackbox_exporter#477] opened 2019-05-17 09:31 UTC
### blackbox_exporter version: blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:32:31
  go version:       go1.11.5

### What is the blackbox.yml module config.
modules:
  http_2xx:
    http:
      preferred_ip_protocol: ip4
    prober: http
    timeout: 5s

### What is the prometheus.yml scrape config.
- job_name: example1.com-https
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: 127.0.0.1:9115
      target_label: __address__
    static_configs:
    - targets:
      - https://example1.com

### What logging output did you get from adding `&debug=true` to the probe URL?
Logs for the probe:
ts=2019-05-17T09:22:21.16305696Z caller=main.go:118 module=http_2xx target=https://example1.com level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2019-05-17T09:22:21.163303334Z caller=utils.go:42 module=http_2xx target=https://example1.com level=info msg="Resolving target address" ip_protocol=ip4
ts=2019-05-17T09:22:21.164520566Z caller=utils.go:75 module=http_2xx target=https://example1.com level=info msg="Resolved target address" ip=XX.XX.XX.XX
ts=2019-05-17T09:22:21.164636219Z caller=http.go:349 module=http_2xx target=https://example1.com level=info msg="Making HTTP request" url=https://[XX.XX.XX.XX] host=example1.com
ts=2019-05-17T09:22:21.224206983Z caller=http.go:305 module=http_2xx target=https://example1.com level=info msg="Received redirect" url=https://example2.com
ts=2019-05-17T09:22:21.235696847Z caller=http.go:364 module=http_2xx target=https://example1.com level=error msg="Error for HTTP request" err="Get https://example2.com: x509: certificate is valid for example2.com, not example1.com

### What did you do that produced an error?
Probing example1.com which redirects to example2.com with following redirects set to true.

### What did you expect to see?
probe_succes=1 after following redirection to example2.com

### What did you see instead?
Probing fails, because blackbox except example2.com https certificate to be valid for example1.com.

**Comment by brian-brazil** [comment] 2019-05-17 09:32
Dupe of #237

**Closed by brian-brazil** 2019-05-17 09:32 UTC
