### ISSUE TITLE
Blackbox doesn't start on raspberry pi - Cannot Allocate memory

### ISSUE THREAD

**Issue by snuguru-maestro** [prometheus/blackbox_exporter#820] opened 2021-08-27 23:44 UTC
### Host operating system: output of `uname -a`
Raspberry pi 2B
Linux raspberrypi 5.10.52+ #1441 Tue Aug 3 18:08:18 BST 2021 armv6l GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`

0.19.0 armv6 release. 
I didn't build it.
### What is the blackbox.yml module config.
default
### What is the prometheus.yml scrape config.
N/A
### What logging output did you get from adding `&debug=true` to the probe URL?
N/A
### What did you do that produced an error?
start the program
### What did you expect to see?
Program starts up
### What did you see instead?
pi@raspberrypi:/blackbox_exporter $ ./blackbox_exporter
fatal error: runtime: cannot allocate memory

runtime stack:
runtime.throw(0x6888c0, 0x1f)
        /usr/local/go/src/runtime/panic.go:1117 +0x5c fp=0xbecf05b8 sp=0xbecf05a4 pc=0x47d98
runtime.persistentalloc1(0x80, 0x4, 0xad2cb0, 0x0)
        /usr/local/go/src/runtime/malloc.go:1360 +0x2a8 fp=0xbecf05e8 sp=0xbecf05b8 pc=0x1d320
runtime.persistentalloc.func1()
        /usr/local/go/src/runtime/malloc.go:1314 +0x34 fp=0xbecf0600 sp=0xbecf05e8 pc=0x75510
runtime.persistentalloc(0x80, 0x4, 0xad2cb0, 0x0)
        /usr/local/go/src/runtime/malloc.go:1313 +0x58 fp=0xbecf0620 sp=0xbecf0600 pc=0x1d058
runtime.(*addrRanges).init(0xac4094, 0xad2cb0)
        /usr/local/go/src/runtime/mranges.go:170 +0x40 fp=0xbecf0634 sp=0xbecf0620 pc=0x3ff48
runtime.(*pageAlloc).init(0xac4054, 0xac4050, 0xad2cb0)
        /usr/local/go/src/runtime/mpagealloc.go:314 +0x50 fp=0xbecf0644 sp=0xbecf0634 pc=0x39e78
runtime.(*mheap).init(0xac4050)
        /usr/local/go/src/runtime/mheap.go:726 +0x2b8 fp=0xbecf0654 sp=0xbecf0644 pc=0x370b4
runtime.mallocinit()
        /usr/local/go/src/runtime/malloc.go:480 +0x100 fp=0xbecf0684 sp=0xbecf0654 pc=0x1b3a8
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:635 +0x50 fp=0xbecf06b0 sp=0xbecf0684 pc=0x4ba54
runtime.rt0_go(0xbecf0807, 0x0, 0xbecf081b, 0xbecf082b, 0xbecf083a, 0xbecf0851, 0xbecf085c, 0xbecf0871, 0xbecf087f, 0xbecf0890, ...)
        /usr/local/go/src/runtime/asm_arm.s:163 +0x7c fp=0xbecf06f0 sp=0xbecf06b0 pc=0x7c740

pi@raspberrypi:/blackbox_exporter $ free -h
              total        used        free      shared  buff/cache   available
Mem:          477Mi       185Mi        94Mi       1.0Mi       197Mi       249Mi
Swap:          99Mi       2.0Mi        97Mi

**Comment by electron0zero** [comment] 2024-12-24 18:23
going to close this due to age.

please reopen if this issue can be reproduced on latest release with a system with sufficient free memory.

**Closed by electron0zero** 2024-12-24 18:23 UTC
