### ISSUE TITLE
Metrics are randomly disappearing

### ISSUE THREAD

**Issue by tischenko** [prometheus/blackbox_exporter#84] opened 2016-12-05 09:46 UTC
blackbox_exporter 0.3.0 / prometheus 1.4.1

I've faced the issue when blackbox_exporter starts returning _probe_success 0_ for random hosts after several hours/days of correct functioning.

Prometheus' configuration:
```
global:
  scrape_interval: 60s
  scrape_timeout: 20s
  external_labels:
    monitor: 'tvdashboard'

scrape_configs:
  - job_name: 'blackbox_devmetrics'
    metrics_path: /probe
    params:
      module: [http_devmetrics]
    static_configs:
      - targets:
        - devmetrics.hostname.com
    relabel_configs: &relabel
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9115  # blackbox_exporter
  - job_name: 'blackbox_rally'
    metrics_path: /probe
    params:
      module: [http_rally]
    static_configs:
      - targets:
        - rally1.rallydev.com/slm/login.op
    relabel_configs: *relabel
  - job_name: 'blackbox_jira'
    metrics_path: /probe
    params:
      module: [http_jira]
    static_configs:
      - targets:
        - jira.hostname.com/login.jsp?os_destination=%2Fsecure%2FDashboard.jspa
    relabel_configs: *relabel
  - job_name: 'blackbox_confluence'
    metrics_path: /probe
    params:
      module: [http_confluence]
    static_configs:
      - targets:
        - confluence.hostname.com/login.action
    relabel_configs: *relabel
```

blackbox_exporter's configuration
```
modules:
  http_devmetrics:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: &headers
        Accept-Language: en-US
        User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "username"
      tls_config: &tls_config
        insecure_skip_verify: true
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
  http_rally:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: *headers
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "Sign in"
      tls_config: *tls_config
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
  http_jira:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: *headers
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "login-form-username"
      tls_config: *tls_config
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
  http_confluence:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: *headers
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "Username"
      tls_config: *tls_config
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
```

I've tried using Prometheus' web UI and CLI to debug. I've noticed that all the targets are active ("up") in Prometheus, but at the same time when I want to get a value of _probe_http_status_code_ metric, I see it only for several (randomly selected) targets, but not for all (this is my expected behavior).

When I'm using CLI, I got the same result for the hosts that aren't displaying in Prometheus UI:
```
$ curl "http://127.0.0.1:9115/probe?module=http_devmetrics&target=devmetrics.hostname.com"
probe_duration_seconds 0.001795
probe_success 0
```
So seems like the problem is in blackbox_exporter but not in Prometheus itself.

On the other hand, if using just curl, I see that my service is up and running:
```
$ curl -L -k "http://devmetrics.hostname.com" | grep -o username
username
```

I'm doing _curl_ on the same machine where blackbox_exporter is running to eliminate any network issues.

This problem occurs periodically and in most cases is solved by blackbox_exporter restarting.

**Comment by brian-brazil** [comment] 2016-12-05 09:51
Your curl isn't doing the same thing the blackbox exporter is doing. Can you confirm the exact same http request constructed by hand is succeeding? An strace/tcpdump of the exporter when it's failing may also be illuminating.

**Comment by tischenko** [comment] 2016-12-05 12:01
Ok, I will try to do so when the problem will appear again. I've restarted blackbox_exporter a moment ago and it works OK now. Please, don't close the ticket if possible.

**Comment by tischenko** [comment] 2016-12-07 14:17
I was digging into the problem today.
What I found out is that the problem relates to the limit of opened files. The default value in my system is 1024 file descriptors per process. For unknown reason (I think this is a bug on blackbox_exporter's end), blackbox_exporter hits this limit after several hours/days of performing. Right after I've increased the limit to 4096, it continued working fine even without a restart.
I currently use blackbox_exporter to check the status of about 15 services via standard http module. Don't think that this may be treated as a serious load, so such behavior looks a bit weird to me.

```
Dec 07 05:48:33 server-tvdashboard blackbox_exporter[13973]: time="2016-12-07T05:48:33-08:00" level=warning msg="Error for HTTP request to http://192.168.21.44: Get http://192.168.21.44: dial tcp4 192.168.21.44:80: socket: too many open files" source="http.go:159"
Dec 07 05:48:34 server-tvdashboard blackbox_exporter[13973]: 2016/12/07 05:48:34 http: Accept error: accept tcp 127.0.0.1:9115: accept4: too many open files; retrying in 5ms 
```

**Comment by brian-brazil** [comment] 2016-12-07 14:51
That sounds like a FD leak. Looks like it snuck in when https support was added, we need to disable keepalives on the http.Transport.

**Comment by pj42** [comment] 2017-01-11 09:43
I have fixed this. I disabled keepalives as Brian suggested and confirmed working for me. Before the fix it twice had 1000 connections still open after 6 hours and after applying the fix there were no connections still open after 12 hours. See pull request:

https://github.com/prometheus/blackbox_exporter/pull/99

**Comment by pj42** [comment] 2017-01-11 10:21
Now merged to master :)

https://github.com/prometheus/blackbox_exporter/commit/78897d2b92f66d50f0c17731baf5a42e7d1b4a0d

**Closed** 2017-03-20 16:31 UTC
Labels: bug
