### ISSUE TITLE
TLS SNI not supported in TCP mode

### ISSUE THREAD

**Issue by marcan** [prometheus/blackbox_exporter#224] opened 2017-09-11 09:06 UTC
This works:
`/probe?target=https://marcan.st&module=http_2xx`

But this doesn't:
`/probe?target=marcan.st:443&module=tls_connect`

`level=error msg="Error dialing TCP: x509: certificate has expired or is not yet valid" source="tcp.go:78"`

marcan.st:443 serves up a valid Let's Encrypt cert when provided with proper SNI, but otherwise serves up an old, untrusted, expired cert. tcpdump confirms no SNI is being sent in TCP mode, though it is in HTTP mode.

Version: 0.8.1
Config:
```
  http_2xx:
    prober: http
    timeout: 5s
    http:
      tls_config:
        insecure_skip_verify: false
  tls_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: ip4
      tls: true
      tls_config:
        insecure_skip_verify: false

**Comment by brian-brazil** [comment] 2017-09-11 17:29
Have you tried specifying the servername option?

**Comment by marcan** [comment] 2017-09-19 10:10
That works, but it should be defaulting to the probe target. Otherwise you need a separate config for every target you want to monitor.

**Comment by brian-brazil** [comment] 2017-09-19 10:54
Dupe of #225

**Closed by brian-brazil** 2017-09-19 10:54 UTC
